CREATE TABLE wallet (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    version BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);